# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhouseholdmember',
            name='slug',
            field=models.CharField(db_index=True, editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='slug',
            field=models.CharField(db_index=True, editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
    ]
