# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170221_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentmember',
            name='next_appt_datetime_source',
            field=models.CharField(choices=[('neighbour', 'Neighbour'), ('household member', 'Household Member'), ('hbc', 'Field RA'), ('OTHER', 'Other')], max_length=25, verbose_name='Appointment date suggested by?'),
        ),
        migrations.AlterField(
            model_name='historicalabsentmember',
            name='next_appt_datetime_source',
            field=models.CharField(choices=[('neighbour', 'Neighbour'), ('household member', 'Household Member'), ('hbc', 'Field RA'), ('OTHER', 'Other')], max_length=25, verbose_name='Appointment date suggested by?'),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='internal_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifier to track member between surveys, is the id of the member's first appearance in the table."),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='relation',
            field=models.CharField(choices=[('head', 'HEAD of HOUSEHOLD'), ('aunt', 'Aunt'), ('brother', 'Brother'), ('brother-in-law', 'Brother in-law'), ('cousin', 'Cousin'), ('daughter', 'Daughter'), ('daughter-in-law', 'Daughter-in-law'), ('employee', 'Employee'), ('family_friend', 'Family friend'), ('father', 'Father'), ('father-in-law', 'Father-in-law'), ('friend', 'Friend'), ('granddaughter', 'Granddaughter'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('grandson', 'Grandson'), ('great-granddaughter', 'Great-Granddaughter'), ('great-grandfather', 'Great-Grandfather'), ('great-grandmother', 'Great-Grandmother'), ('great-grandson', 'Great-Grandson'), ('helper', 'Helper'), ('housemaid', 'Housemaid'), ('housemate', 'Housemate'), ('husband', 'Husband'), ('mother', 'Mother'), ('mother-in-law', 'Mother-in-law'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('partner', 'Partner'), ('sister', 'Sister'), ('sister-in-law', 'Sister-in-law'), ('son', 'Son'), ('son-in-law', 'Son-in-law'), ('uncle', 'Uncle'), ('wife', 'Wife'), ('unknown', 'UNKNOWN')], help_text='Relation to head of household', max_length=35, null=True, verbose_name='Relation to head of household'),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='subject_identifier_as_pk',
            field=models.CharField(default=edc_base.utils.get_uuid, editable=False, max_length=32, verbose_name='Subject Identifier as pk'),
        ),
        migrations.AlterField(
            model_name='historicalrefusedmember',
            name='reason',
            field=models.CharField(choices=[("I don't have time", "I don't have time"), ("I don't want to answer the questions", "I don't want to answer the questions"), ("I don't want to have the blood drawn", "I don't want to have the blood drawn"), ('I am afraid my information will not be private', 'I am afraid my information will not be private'), ('Fear of needles', 'Fear of needles'), ('Illiterate does not want a witness', 'Illiterate does not want a witness'), ('I already know I am HIV-positive', 'I already know I am HIV-positive'), ('I already know my status', 'I already know my status'), ('I am afraid of testing', 'I am afraid of testing'), ("I don't want to take part", "I don't want to take part"), ("I haven't had a chance to think about it", "I haven't had a chance to think about it"), ('Have a newly born baby, not permitted', 'Have a newly born baby, not permitted'), ('I am not ready to test', 'I am not ready to test'), ('Already on HAART', 'Already on HAART'), ('I want to test where i always test', 'I want to test where i always test'), ("I already know my partner's status, no need to test", "I already know my partner's status, no need to test"), ('The appointment was not honoured', 'The appointment was not honoured'), ('not_sure', 'I am not sure'), ('OTHER', 'Other, specify:'), ('DWTA', "Don't want to answer")], max_length=50, verbose_name='We respect your decision to decline. It would help us improve the study if you could tell us the main reason you do not want to participate in this study?'),
        ),
        migrations.AlterField(
            model_name='historicalrefusedmemberhistory',
            name='reason',
            field=models.CharField(choices=[("I don't have time", "I don't have time"), ("I don't want to answer the questions", "I don't want to answer the questions"), ("I don't want to have the blood drawn", "I don't want to have the blood drawn"), ('I am afraid my information will not be private', 'I am afraid my information will not be private'), ('Fear of needles', 'Fear of needles'), ('Illiterate does not want a witness', 'Illiterate does not want a witness'), ('I already know I am HIV-positive', 'I already know I am HIV-positive'), ('I already know my status', 'I already know my status'), ('I am afraid of testing', 'I am afraid of testing'), ("I don't want to take part", "I don't want to take part"), ("I haven't had a chance to think about it", "I haven't had a chance to think about it"), ('Have a newly born baby, not permitted', 'Have a newly born baby, not permitted'), ('I am not ready to test', 'I am not ready to test'), ('Already on HAART', 'Already on HAART'), ('I want to test where i always test', 'I want to test where i always test'), ("I already know my partner's status, no need to test", "I already know my partner's status, no need to test"), ('The appointment was not honoured', 'The appointment was not honoured'), ('not_sure', 'I am not sure'), ('OTHER', 'Other, specify:'), ('DWTA', "Don't want to answer")], max_length=50, verbose_name='We respect your decision to decline. It would help us improve the study if you could tell us the main reason you do not want to participate in this study?'),
        ),
        migrations.AlterField(
            model_name='historicalundecidedmember',
            name='next_appt_datetime_source',
            field=models.CharField(choices=[('neighbour', 'Neighbour'), ('household member', 'Household Member'), ('hbc', 'Field RA'), ('OTHER', 'Other')], max_length=25, verbose_name='Appointment date suggested by?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='internal_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifier to track member between surveys, is the id of the member's first appearance in the table."),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='relation',
            field=models.CharField(choices=[('head', 'HEAD of HOUSEHOLD'), ('aunt', 'Aunt'), ('brother', 'Brother'), ('brother-in-law', 'Brother in-law'), ('cousin', 'Cousin'), ('daughter', 'Daughter'), ('daughter-in-law', 'Daughter-in-law'), ('employee', 'Employee'), ('family_friend', 'Family friend'), ('father', 'Father'), ('father-in-law', 'Father-in-law'), ('friend', 'Friend'), ('granddaughter', 'Granddaughter'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('grandson', 'Grandson'), ('great-granddaughter', 'Great-Granddaughter'), ('great-grandfather', 'Great-Grandfather'), ('great-grandmother', 'Great-Grandmother'), ('great-grandson', 'Great-Grandson'), ('helper', 'Helper'), ('housemaid', 'Housemaid'), ('housemate', 'Housemate'), ('husband', 'Husband'), ('mother', 'Mother'), ('mother-in-law', 'Mother-in-law'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('partner', 'Partner'), ('sister', 'Sister'), ('sister-in-law', 'Sister-in-law'), ('son', 'Son'), ('son-in-law', 'Son-in-law'), ('uncle', 'Uncle'), ('wife', 'Wife'), ('unknown', 'UNKNOWN')], help_text='Relation to head of household', max_length=35, null=True, verbose_name='Relation to head of household'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='subject_identifier_as_pk',
            field=models.CharField(default=edc_base.utils.get_uuid, editable=False, max_length=32, verbose_name='Subject Identifier as pk'),
        ),
        migrations.AlterField(
            model_name='refusedmember',
            name='reason',
            field=models.CharField(choices=[("I don't have time", "I don't have time"), ("I don't want to answer the questions", "I don't want to answer the questions"), ("I don't want to have the blood drawn", "I don't want to have the blood drawn"), ('I am afraid my information will not be private', 'I am afraid my information will not be private'), ('Fear of needles', 'Fear of needles'), ('Illiterate does not want a witness', 'Illiterate does not want a witness'), ('I already know I am HIV-positive', 'I already know I am HIV-positive'), ('I already know my status', 'I already know my status'), ('I am afraid of testing', 'I am afraid of testing'), ("I don't want to take part", "I don't want to take part"), ("I haven't had a chance to think about it", "I haven't had a chance to think about it"), ('Have a newly born baby, not permitted', 'Have a newly born baby, not permitted'), ('I am not ready to test', 'I am not ready to test'), ('Already on HAART', 'Already on HAART'), ('I want to test where i always test', 'I want to test where i always test'), ("I already know my partner's status, no need to test", "I already know my partner's status, no need to test"), ('The appointment was not honoured', 'The appointment was not honoured'), ('not_sure', 'I am not sure'), ('OTHER', 'Other, specify:'), ('DWTA', "Don't want to answer")], max_length=50, verbose_name='We respect your decision to decline. It would help us improve the study if you could tell us the main reason you do not want to participate in this study?'),
        ),
        migrations.AlterField(
            model_name='refusedmemberhistory',
            name='reason',
            field=models.CharField(choices=[("I don't have time", "I don't have time"), ("I don't want to answer the questions", "I don't want to answer the questions"), ("I don't want to have the blood drawn", "I don't want to have the blood drawn"), ('I am afraid my information will not be private', 'I am afraid my information will not be private'), ('Fear of needles', 'Fear of needles'), ('Illiterate does not want a witness', 'Illiterate does not want a witness'), ('I already know I am HIV-positive', 'I already know I am HIV-positive'), ('I already know my status', 'I already know my status'), ('I am afraid of testing', 'I am afraid of testing'), ("I don't want to take part", "I don't want to take part"), ("I haven't had a chance to think about it", "I haven't had a chance to think about it"), ('Have a newly born baby, not permitted', 'Have a newly born baby, not permitted'), ('I am not ready to test', 'I am not ready to test'), ('Already on HAART', 'Already on HAART'), ('I want to test where i always test', 'I want to test where i always test'), ("I already know my partner's status, no need to test", "I already know my partner's status, no need to test"), ('The appointment was not honoured', 'The appointment was not honoured'), ('not_sure', 'I am not sure'), ('OTHER', 'Other, specify:'), ('DWTA', "Don't want to answer")], max_length=50, verbose_name='We respect your decision to decline. It would help us improve the study if you could tell us the main reason you do not want to participate in this study?'),
        ),
        migrations.AlterField(
            model_name='undecidedmember',
            name='next_appt_datetime_source',
            field=models.CharField(choices=[('neighbour', 'Neighbour'), ('household member', 'Household Member'), ('hbc', 'Field RA'), ('OTHER', 'Other')], max_length=25, verbose_name='Appointment date suggested by?'),
        ),
    ]
