# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170316_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='subject_identifier_as_pk',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='subject_identifier_as_pk',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
