# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20170316_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='inability_to_participate',
            field=models.CharField(choices=[('able', 'ABLE to participate'), ('Mental Incapacity', 'Mental Incapacity'), ('Deaf/Mute', 'Deaf/Mute'), ('Too sick', 'Too sick'), ('Incarcerated', 'Incarcerated'), ('OTHER', 'Other, specify.'), ('N/A', 'Not applicable')], help_text='Participant can only participate if ABLE is selected. (Any other reason make the participant unable to take part in the informed consent process)', max_length=17, null=True, verbose_name='Do any of the following reasons apply to the participant?'),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='personal_details_changed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], help_text='personal details (name/surname)', max_length=10, null=True, verbose_name='Have your personal details (name/surname) changed since the last time we visited you?'),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='present_today',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, null=True, verbose_name='Is the member present today?'),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='relation',
            field=models.CharField(choices=[('head', 'HEAD of HOUSEHOLD'), ('aunt', 'Aunt'), ('brother', 'Brother'), ('brother-in-law', 'Brother in-law'), ('cousin', 'Cousin'), ('daughter', 'Daughter'), ('daughter-in-law', 'Daughter-in-law'), ('employee', 'Employee'), ('family_friend', 'Family friend'), ('father', 'Father'), ('father-in-law', 'Father-in-law'), ('friend', 'Friend'), ('granddaughter', 'Granddaughter'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('grandson', 'Grandson'), ('great-granddaughter', 'Great-Granddaughter'), ('great-grandfather', 'Great-Grandfather'), ('great-grandmother', 'Great-Grandmother'), ('great-grandson', 'Great-Grandson'), ('helper', 'Helper'), ('housemaid', 'Housemaid'), ('housemate', 'Housemate'), ('husband', 'Husband'), ('mother', 'Mother'), ('mother-in-law', 'Mother-in-law'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('partner', 'Partner'), ('sister', 'Sister'), ('sister-in-law', 'Sister-in-law'), ('son', 'Son'), ('son-in-law', 'Son-in-law'), ('uncle', 'Uncle'), ('wife', 'Wife'), ('unknown', 'UNKNOWN'), ('N/A', 'Not Applicable')], help_text='Relation to head of household', max_length=35, null=True, verbose_name='Relation to head of household'),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='study_resident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], help_text='If participant has moved into the community in the past 12 months, then since moving in has the participant typically spent 3 or more nights per month in this community.', max_length=17, null=True, verbose_name='In the past 12 months, have you typically spent 3 or more nights per month in this community? '),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='survival_status',
            field=models.CharField(choices=[('alive', 'Alive'), ('dead', 'Deceased'), ('unknown', 'Unknown')], default='alive', max_length=10, null=True, verbose_name='Survival status'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='inability_to_participate',
            field=models.CharField(choices=[('able', 'ABLE to participate'), ('Mental Incapacity', 'Mental Incapacity'), ('Deaf/Mute', 'Deaf/Mute'), ('Too sick', 'Too sick'), ('Incarcerated', 'Incarcerated'), ('OTHER', 'Other, specify.'), ('N/A', 'Not applicable')], help_text='Participant can only participate if ABLE is selected. (Any other reason make the participant unable to take part in the informed consent process)', max_length=17, null=True, verbose_name='Do any of the following reasons apply to the participant?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='personal_details_changed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], help_text='personal details (name/surname)', max_length=10, null=True, verbose_name='Have your personal details (name/surname) changed since the last time we visited you?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='present_today',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, null=True, verbose_name='Is the member present today?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='relation',
            field=models.CharField(choices=[('head', 'HEAD of HOUSEHOLD'), ('aunt', 'Aunt'), ('brother', 'Brother'), ('brother-in-law', 'Brother in-law'), ('cousin', 'Cousin'), ('daughter', 'Daughter'), ('daughter-in-law', 'Daughter-in-law'), ('employee', 'Employee'), ('family_friend', 'Family friend'), ('father', 'Father'), ('father-in-law', 'Father-in-law'), ('friend', 'Friend'), ('granddaughter', 'Granddaughter'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('grandson', 'Grandson'), ('great-granddaughter', 'Great-Granddaughter'), ('great-grandfather', 'Great-Grandfather'), ('great-grandmother', 'Great-Grandmother'), ('great-grandson', 'Great-Grandson'), ('helper', 'Helper'), ('housemaid', 'Housemaid'), ('housemate', 'Housemate'), ('husband', 'Husband'), ('mother', 'Mother'), ('mother-in-law', 'Mother-in-law'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('partner', 'Partner'), ('sister', 'Sister'), ('sister-in-law', 'Sister-in-law'), ('son', 'Son'), ('son-in-law', 'Son-in-law'), ('uncle', 'Uncle'), ('wife', 'Wife'), ('unknown', 'UNKNOWN'), ('N/A', 'Not Applicable')], help_text='Relation to head of household', max_length=35, null=True, verbose_name='Relation to head of household'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='study_resident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], help_text='If participant has moved into the community in the past 12 months, then since moving in has the participant typically spent 3 or more nights per month in this community.', max_length=17, null=True, verbose_name='In the past 12 months, have you typically spent 3 or more nights per month in this community? '),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='survival_status',
            field=models.CharField(choices=[('alive', 'Alive'), ('dead', 'Deceased'), ('unknown', 'Unknown')], default='alive', max_length=10, null=True, verbose_name='Survival status'),
        ),
    ]
